services:
  accounts:
    image: "ak0705/accounts:1.0"
    container_name: accounts-ms
    ports:
      - "8080:8080" 
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mircoservice-network
  loans:
    image: "ak0705/loans:1.0"
    container_name: loans-ms
    ports:
      - "8090:8090" 
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mircoservice-network
  cards:
    image: "ak0705/cards:1.0"
    container_name: cards-ms
    ports:
      - "9000:9000" 
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mircoservice-network
networks:
  mircoservice-network:
    driver: "bridge"
    